import "@/app/globals.css";
import { Inter } from "next/font/google";
import Provider from "../../../context/Provider";
import Nav from "../components/Navs/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "travu",
  description: "Generated by create next app",
};

export default function dashboard({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body className={`bg-white ${inter.className}`}>
          <Nav />
          {children}
        </body>
      </Provider>
    </html>
  );
}
